### ISSUE TITLE
The "Get your listener from the ItemViewHolder" in the readme is poorly documented.

### ISSUE THREAD

**Issue by ColdSauce** [ribot/easy-adapter#25]
There seems to be a method call to a getListeners() method yet there is no method declaration for such a method. (At least for RecyclerViews)

**Comment by jsonfry** [comment]
Good afternoon! Thanks for the feedback, what exactly are you unsure about?

Inside your `ItemViewHolder` you can call `getListener(MyListenerClassName.class)` to get your listener.

You set it when you create your `EasyAdapter` or `EasyRecyclerAdapter`.
