### ISSUE TITLE
Why not support adapter.getFilter ()?

### ISSUE THREAD

**Issue by jhonvidal** [ribot/easy-adapter#28]
How to turn ArrayAdapter?
to Acknowledge getFilter()
How to implement a search EasyAdapter?

Help Please :)

**Comment by ivacf** [comment]
Hi, `EasyAdapter` extends `BaseAdapter` so it cannot be cast to a `ArrayAdapter`. 
If you want to use `getFilter()` you will have to create your own adapter that extends `BaseEasyAdapter` and implements `android.widget.Filterable`

**Comment by jhonvidal** [comment]
thanks !!

**Comment by MFlisar** [comment]
Here's a gist for those who want to use a filter for `RecyclerView`:

https://gist.github.com/MFlisar/846e9607ffb6b330701f

It supports animations for insert, delete and move.

just call

    adapter.filter(new IPredicate<T>() {
        @Override
         public boolean apply(T data) {
             // return true if data should be part of the filtered list
         }
    });

Btw, you can include this directly into your library if you like it and want to...
