### ISSUE TITLE
Consider adding support for drop down views

### ISSUE THREAD

**Issue by grodin** [ribot/easy-adapter#29]
The library is great, but I think one more thing could be a great addition: supporting drop down views as well as item views, for use with `Spinners`. Currently, if an `EasyAdapter` is used with a `Spinner`, the same view is used for both the drop down and 'main view', which works OK, but isn't always what you want.

I need to get some sleep right now, but I'll have a bit more of a think about how it might work tomorrow. I'd be interested in trying to implement it if it's something you'd accept.

**Comment by ivacf** [comment]
Hi, supporting drop down views for Spinners could be a nice addition to the library. I'll think about it when I have some free time and see if there is a nice way of integrating this feature.

I guess we would need a new adapter for spinners e.g. `EasySpinnerAdapter` that implements [SpinnerAdapter](http://developer.android.com/reference/android/widget/SpinnerAdapter.html) and takes two different holders.
