### ISSUE TITLE
Usage with stable ids

### ISSUE THREAD

**Issue by MFlisar** [ribot/easy-adapter#37]
Is that somehow possible? As I need to provide custom ids, I could not find a way to do it with your adapter...

**Comment by ivacf** [comment]
You should be able to do it by extending the `BaseEasyAdapter`. When you extend this base adapter you have to provide your own data structure and then implement `getCount()`, `getItemId()` and `getItem()`. You can also override `hasStableIds()`. 

Check the [`EasyAdapter.java`](https://github.com/ribot/easy-adapter/blob/5205f177039b926e881ac49d3405930d737805f5/library/src/main/java/uk/co/ribot/easyadapter/EasyAdapter.java) source code for an example of how to extend `BaseEasyAdapter`.

**Comment by MFlisar** [comment]
Of course. I anyway have already an extended version that supports filtering... Don't know why I did not think about that. Thanks
