### ISSUE TITLE
Bypass injections with manual calls to support usage in libraries

### ISSUE THREAD

**Issue by MFlisar** [ribot/easy-adapter#38]
Is that somehow possible? If I want to write some reuseable adapters in a library, this is not possible, because in libraries I do not have stable resource ids.

So the solution is to do what `@LayoutId`, `@LayoutId` and `@ViewId` does manually.

Is that somehow possible? Actually I can't find a way for replacing `@LayoutId`, the rest is not the problem I think...

**Comment by ivacf** [comment]
No, this is not possible at the moment. Using `@LayoutId` is required

**Comment by MFlisar** [comment]
Ok. Just wanted to make sure if I oversaw something
